### ISSUE TITLE
Need to handle request parameters

### ISSUE THREAD

**Issue by jaschweder** [vesparny/silex-simple-rest#10]
how handle request parameters ?

One solution is to register SessionServiceProvider
$app->register(new Silex\Provider\SessionServiceProvider());

**Comment by vesparny** [comment]
You can see here how to get parameters from request:
https://github.com/vesparny/silex-simple-rest/blob/master/src/App/Controllers/NotesController.php#L50

If you need session management, you need the SessionServiceProvider too.

**Comment by vesparny** [comment]
please refer to the Request class docs http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Request.html
