### ISSUE TITLE
Show stack trace only in debug mode.

### ISSUE THREAD

**Issue by bocharsky-bw** [vesparny/silex-simple-rest#15]
Its stongly recommended do **not** show [stack trace](https://github.com/vesparny/silex-simple-rest/blob/master/src/app.php#L73) to the everyone API user. You should show this info only if debug mode is enabled, otherwise don't show it.

For example:

``` php
    $data = [
        'statusCode' => $code,
        'message' => $e->getMessage(),
    ];

    if ($app['debug']) {
        $data['stacktrace'] = $e->getTraceAsString();
    }

    return new JsonResponse($data);
```

**Comment by bocharsky-bw** [comment]
@vesparny Was it implemented?

**Comment by vesparny** [comment]
I do not know.
I close the issue because it was 2 years old.

**Comment by vesparny** [comment]
I am not actively maintaining this project anymore, but I am happy to review and merge PRs :)

Thanks for your help
